import { SIZE, Direction, DIR_NAMES, InstructionTile, ExecutionTile, WinCondition, Simulation, createDemoLevel, cloneLevel, key, cell } from './core.js';

const PLAYER_TYPES = [InstructionTile.FORWARD, InstructionTile.LEFT, InstructionTile.RIGHT, InstructionTile.TRACK, InstructionTile.OBSERVER, InstructionTile.CLONE, InstructionTile.CLONE_POINT];
const TYPE_NAMES = { forward: '前进', left: '左转', right: '右转', track: '轨道', observer: '观察者', clone: '克隆', clonePoint: '克隆位点' };
let level = createDemoLevel(); let inventory = cloneLevel(level.inventory); let simulation = new Simulation(level); let designMode = false; let running = false; let timer = null;
let selected = { type: InstructionTile.FORWARD, direction: Direction.RIGHT };
const $ = (id) => document.getElementById(id); const instructionGrid = $('instructionGrid'), executionGrid = $('executionGrid');
const instructionPalette = [[InstructionTile.FORWARD, '+', '前进'], [InstructionTile.LEFT, '↶', '左转'], [InstructionTile.RIGHT, '↷', '右转'], [InstructionTile.TRACK, '➜', '轨道'], [InstructionTile.OBSERVER, 'observer', '观察者'], [InstructionTile.CLONE, '⧉', '克隆'], [InstructionTile.CLONE_POINT, '◇', '克隆位点'], [InstructionTile.BARRIER, '▧', '屏障'], ['erase', '×', '单格清除']];
const executionPalette = [[ExecutionTile.RED, '', '红色'], [ExecutionTile.BLUE, '', '蓝色'], [ExecutionTile.FINISH, '★', '终点'], [ExecutionTile.WALL, '', '墙体'], ['execRobot', '◈', '执行机器人'], ['eraseExecution', '×', '单格清除']];
const eliminationPalette = [[ExecutionTile.RED, '', '红色'], [ExecutionTile.BLUE, '', '蓝色'], ['eraseExecution', '×', '单格清除']];

function isEliminationLevel() { return level.meta?.winCondition === WinCondition.ELIMINATE_INSTRUCTION_ROBOTS; }
function ensurePlayableSelection() {
  if (designMode) return;
  const allowed = isEliminationLevel() ? eliminationPalette.map(([type]) => type) : [...PLAYER_TYPES, 'erase'];
  if (!allowed.includes(selected.type)) selected = { type: allowed[0], direction: Direction.RIGHT };
}

function observerMarkup(direction = Direction.UP) {
  return `<svg class="observer-glyph" viewBox="0 0 48 48" style="--direction:${direction * 90}deg" role="img" aria-label="观察者：白色向前、红色向左、蓝色向右">
    <path class="observer-stem" d="M24 29V12M11 29H37" />
    <circle class="observer-port observer-white" cx="24" cy="9" r="7" /><circle class="observer-port observer-red" cx="8" cy="29" r="7" /><circle class="observer-port observer-blue" cx="40" cy="29" r="7" />
  </svg>`;
}
function turnMarkup(type) {
  const clockwise = type === InstructionTile.RIGHT;
  const arrows = clockwise
    ? '<path d="M30 7l-7-4v8zM41 30l-4-7h8zM18 41l7-4v8zM7 18l4 7H3z" />'
    : '<path d="M18 7l7 4V3zM41 18l4 7h-8zM30 41l-7-4v8zM7 30l4-7H3z" />';
  const label = clockwise ? '右转：顺时针转 90 度' : '左转：逆时针转 90 度';
  return `<svg class="turn-glyph ${clockwise ? 'turn-right' : 'turn-left'}" viewBox="0 0 48 48" role="img" aria-label="${label}"><circle cx="24" cy="24" r="17" />${arrows}</svg>`;
}
function iconMarkup(type, icon, direction = Direction.UP) { if (type === InstructionTile.OBSERVER) return observerMarkup(direction); if (type === InstructionTile.LEFT || type === InstructionTile.RIGHT) return turnMarkup(type); if (type === InstructionTile.TRACK || type === 'execRobot') return DIR_NAMES[direction]; return icon; }
function tileLabel(tile) { return ({ forward: '+', left: '↶', right: '↷', clone: '⧉', clonePoint: '◇', barrier: '', finish: '★', wall: '', white: '', red: '', blue: '' })[tile.type] ?? ''; }
function isInstructionTile(type) { return Object.values(InstructionTile).includes(type) || type === 'erase'; }
function isExecutionTile(type) { return Object.values(ExecutionTile).includes(type) || type === 'execRobot' || type === 'eraseExecution'; }
function setTileContent(button, tile) { if (tile.type === InstructionTile.OBSERVER) button.innerHTML = observerMarkup(tile.direction ?? Direction.UP); else if (tile.type === InstructionTile.LEFT || tile.type === InstructionTile.RIGHT) button.innerHTML = turnMarkup(tile.type); else if (tile.type === InstructionTile.TRACK) button.textContent = DIR_NAMES[tile.direction ?? Direction.UP]; else button.textContent = tileLabel(tile); }
function normalizeLevel(data) { const base = createDemoLevel(); const normalized = { ...base, ...data, meta: { ...base.meta, ...(data.meta || {}) }, inventory: { ...base.inventory, ...(data.inventory || {}) }, instruction: data.instruction || base.instruction, execution: data.execution || base.execution }; normalized.inventory.clonePoint = Math.min(1, Math.max(0, Number(normalized.inventory.clonePoint) || 0)); return normalized; }
function notice(message) { $('saveNotice').textContent = message; }
async function api(path, options) { const response = await fetch(`/api/${path}`, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
function levelFileName() { return `${level.meta.id}-${level.meta.name}`; }
function progressFileName() { return `progress-${levelFileName()}`; }
function buildProgress(status = '进行中') { return { level: cloneLevel(level), playerTiles: cloneLevel(level.instruction.tiles), playerExecutionTiles: cloneLevel(level.execution.tiles), inventory: cloneLevel(inventory), status, savedAt: new Date().toISOString() }; }
async function saveProgress(overwrite = false) { if (typeof overwrite !== 'boolean') overwrite = false; try { const result = await api(`saves/${progressFileName()}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-Overwrite': String(overwrite) }, body: JSON.stringify(buildProgress()) }); notice(`${result.overwritten ? '已覆写' : '已新建'}当前关卡的游玩进度。`); } catch (error) { if (error.message.includes('already exists')) { const file = `saves/${progressFileName()}.json`; if (window.confirm(`“${file}” 已存在。确定要用当前进度覆写它吗？`)) return saveProgress(true); notice('已取消覆写游玩进度。'); } else notice(`保存失败：${error.message}`); } }
async function restoreProgress() { try { const data = await api(`saves/${progressFileName()}`); level = normalizeLevel(data.level); level.instruction.tiles = data.playerTiles; if (data.playerExecutionTiles) level.execution.tiles = data.playerExecutionTiles; inventory = data.inventory; reset(); notice(`已读取当前关卡的${data.status || '当前'}进度。`); } catch (error) { notice(`读取失败：${error.message}`); } }
function clearHistoryKey() { return `${level.meta.id}-${level.meta.name}`; }
async function saveClearHistory() { try { const result = await api(`cleared/history/${clearHistoryKey()}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(buildProgress('已通关')) }); notice(result.duplicate ? '本次通关状态与历史记录相同，未重复保存。' : `通关数据已保存至 ${result.file}。`); } catch (error) { notice(`通关存档失败：${error.message}`); } }
async function restoreClearedProgress(file) { try { const data = await api(`cleared/history/${clearHistoryKey()}/${file.replace(/\.json$/, '')}`); level = normalizeLevel(data.level); level.instruction.tiles = data.playerTiles; if (data.playerExecutionTiles) level.execution.tiles = data.playerExecutionTiles; inventory = data.inventory; reset(); $('levelDialog').close(); notice('已读取该条通关历史。'); } catch (error) { notice(`读取失败：${error.message}`); } }
async function saveLevel(overwrite = false) { try { level.inventory = cloneLevel(inventory); const result = await api(`levels/${levelFileName()}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-Overwrite': String(overwrite) }, body: JSON.stringify(level) }); notice(`${result.overwritten ? '已覆写' : '已新建'}关卡文件 ${result.file}。`); } catch (error) { if (error.message.includes('already exists')) { const file = `levels/${levelFileName()}.json`; if (window.confirm(`“${file}” 已存在。确定要用当前设计覆写它吗？`)) return saveLevel(true); notice('已取消覆写关卡。'); } else notice(`保存失败：${error.message}`); } }
async function openLevelDialog() {
  const list = $('levelList'); $('levelDialog').querySelector('h2').textContent = '读取关卡'; list.textContent = '正在读取关卡…'; $('levelDialog').showModal();
  try { const files = await api('levels'); list.replaceChildren(...files.map((file) => { const button = document.createElement('button'); button.className = 'level-choice'; button.textContent = file.replace(/\.json$/, ''); button.onclick = () => loadLevel(file.replace(/\.json$/, '')); return button; })); if (!files.length) list.textContent = 'levels 文件夹中还没有关卡。'; } catch (error) { list.textContent = `读取关卡列表失败：${error.message}`; }
}
async function openClearHistory() {
  const list = $('levelList'); $('levelDialog').querySelector('h2').textContent = '当前关卡的通关历史'; list.textContent = '正在读取通关历史…'; $('levelDialog').showModal();
  try { const files = await api(`cleared/history/${clearHistoryKey()}`); list.replaceChildren(...files.map((file) => { const button = document.createElement('button'); button.className = 'level-choice'; button.textContent = file.replace(/^clear-/, '').replace(/\.json$/, ''); button.onclick = () => restoreClearedProgress(file); return button; })); if (!files.length) list.textContent = '当前关卡还没有通关历史。'; } catch (error) { list.textContent = `读取通关历史失败：${error.message}`; }
}
async function loadLevel(name) { try { const data = await api(`levels/${name}`); level = normalizeLevel(data); inventory = cloneLevel(level.inventory); reset(); $('levelDialog').close(); notice(`已读取关卡 ${level.meta.id} · ${level.meta.name}。`); } catch (error) { notice(`读取失败：${error.message}`); } }
function renderGrid(element, world) { element.replaceChildren(); const snap = simulation.snapshot(); const visuals = snap.visuals || []; const gridSize = world === 'execution' ? (level.execution.size || SIZE) : SIZE; element.style.setProperty('--grid-size', gridSize); for (let y = 0; y < gridSize; y += 1) for (let x = 0; x < gridSize; x += 1) { const pos = cell(x, y); const k = key(pos); const storedTile = world === 'instruction' ? level.instruction.tiles[k] : level.execution.tiles[k]; const tile = world === 'instruction' && snap.barriersVoid && storedTile?.type === InstructionTile.BARRIER ? null : storedTile; const button = $('tileTemplate').content.firstElementChild.cloneNode(true); button.dataset.x = x; button.dataset.y = y; button.classList.add(world); if (tile) { button.classList.add(`type-${tile.type}`); setTileContent(button, tile); button.title = tile.type; if (tile.preset && !(world === 'instruction' && isEliminationLevel())) button.classList.add('preset'); } else if (world === 'execution') { button.classList.add('type-white'); button.textContent = ''; } const visual = visuals.find((item) => item.position.x === x && item.position.y === y && ((world === 'instruction' && item.kind !== 'wallBump') || (world === 'execution' && item.kind === 'wallBump'))); if (visual) { button.classList.add(`flash-${visual.kind}`); if (visual.kind === 'collision') button.textContent = ''; } if (world === 'instruction' && snap.active && snap.active.position.x === x && snap.active.position.y === y && !visual) button.append(robot('active', snap.active.direction)); if (world === 'instruction') snap.waiting.forEach((bot) => { if (bot.position.x === x && bot.position.y === y && !visual) button.append(robot('waiting', bot.direction)); }); if (world === 'execution' && snap.execution.position.x === x && snap.execution.position.y === y) button.append(robot('execution-robot', snap.execution.direction)); button.addEventListener('click', () => editCell(world, pos)); element.append(button); } }
function renderInstructionEntry() { const entry = $('instructionEntry'); entry.replaceChildren(); const snap = simulation.snapshot(); const edgeFall = (snap.visuals || []).find((item) => item.kind === 'edgeVoid' && item.position.x === -1 && item.position.y === 0); if (edgeFall) entry.classList.add('flash-edgeVoid'); else entry.classList.remove('flash-edgeVoid'); if (snap.active?.position.x === -1 && snap.active.position.y === 0 && !edgeFall) entry.append(robot('active', snap.active.direction)); }
function robot(className, direction) { const el = document.createElement('i'); el.className = `robot ${className}`; el.textContent = DIR_NAMES[direction]; return el; }
function actionButton(label, className, onClick) { const button = document.createElement('button'); button.className = `palette-action ${className}`; button.textContent = label; button.onclick = onClick; return button; }
function returnToInventory(tile) { if (PLAYER_TYPES.includes(tile.type)) inventory[tile.type] = (inventory[tile.type] || 0) + 1; }
function clearInstructionPlayerTiles() { Object.keys(level.instruction.tiles).forEach((entry) => { const tile = level.instruction.tiles[entry]; if (!tile.preset && tile.type !== InstructionTile.BARRIER) { returnToInventory(tile); delete level.instruction.tiles[entry]; } }); reset(); }
function clearInstructionDesignTiles() { level.instruction.tiles = {}; reset(); }
function clearExecutionTiles() { level.execution.tiles = {}; reset(); }
function clearEliminationExecutionTiles() { Object.keys(level.execution.tiles).forEach((entry) => { if ([ExecutionTile.RED, ExecutionTile.BLUE].includes(level.execution.tiles[entry].type)) delete level.execution.tiles[entry]; }); reset(); }
function paletteButton(type, icon, label) { const button = document.createElement('button'); const directional = type === InstructionTile.TRACK || type === InstructionTile.OBSERVER || type === 'execRobot'; button.className = `palette-item type-${type} ${selected.type === type ? 'selected' : ''}`; button.innerHTML = `<b>${iconMarkup(type, icon, directional && selected.type === type ? selected.direction : Direction.UP)}</b><small>${label}</small>`; button.title = directional ? '再次点击可旋转方向' : label; button.onclick = () => { selected = selected.type === type && directional ? { ...selected, direction: (selected.direction + 1) % 4 } : { type, direction: Direction.RIGHT }; update(); }; return button; }
function renderPalette() {
  const palette = $('palette'); palette.replaceChildren();
  ensurePlayableSelection();
  if (!designMode && isEliminationLevel()) { const group = document.createElement('div'); group.className = 'palette-group player-backpack'; const heading = document.createElement('span'); heading.textContent = '背包 · 无限'; group.append(heading); eliminationPalette.forEach(([type, icon, label]) => group.append(paletteButton(type, icon, label))); group.append(actionButton('一键清理', 'clear-execution', clearEliminationExecutionTiles)); palette.append(group); return; }
  if (!designMode) { const group = document.createElement('div'); group.className = 'palette-group player-backpack'; const heading = document.createElement('span'); heading.textContent = '背包'; group.append(heading); PLAYER_TYPES.filter((type) => (inventory[type] || 0) > 0).forEach((type) => { const item = document.createElement('div'); item.className = 'backpack-item'; item.append(paletteButton(type, tileLabel({ type }), TYPE_NAMES[type])); const count = document.createElement('strong'); count.textContent = inventory[type]; item.append(count); group.append(item); }); group.append(paletteButton('erase', '×', '单格清除'), actionButton('一键清理', 'clear-instruction', clearInstructionPlayerTiles)); palette.append(group); return; }
  [['指令模块', instructionPalette], ['执行模块', executionPalette]].forEach(([title, items]) => { const group = document.createElement('div'); group.className = 'palette-group'; const heading = document.createElement('span'); heading.textContent = title; group.append(heading); items.forEach(([type, icon, label]) => group.append(paletteButton(type, icon, label))); group.append(actionButton('一键清理', title === '指令模块' ? 'clear-instruction' : 'clear-execution', title === '指令模块' ? clearInstructionDesignTiles : clearExecutionTiles)); palette.append(group); });
}
function renderSavePanel() {
  const title = $('saveTitle'); const controls = $('saveControls'); controls.replaceChildren();
  if (designMode) { title.textContent = '关卡设计与文件保存'; const id = document.createElement('input'); id.value = level.meta.id; id.maxLength = 12; id.placeholder = '关卡编号'; id.oninput = () => { level.meta.id = id.value; }; const name = document.createElement('input'); name.value = level.meta.name; name.maxLength = 36; name.placeholder = '关卡名称'; name.oninput = () => { level.meta.name = name.value; }; controls.append(id, name, actionButton('保存关卡文件', 'save-primary', saveLevel), actionButton('读取关卡', 'save-secondary', openLevelDialog)); }
  else { title.textContent = '游玩存档'; controls.append(actionButton('读取关卡', 'save-secondary', openLevelDialog), actionButton('保存当前进度', 'save-primary', saveProgress), actionButton('读取当前进度', 'save-secondary', restoreProgress), actionButton('读取通关历史', 'save-secondary', openClearHistory)); }
}
function renderInventory() { if (!designMode) return; const palette = $('palette'); const group = document.createElement('div'); group.className = 'palette-group design-inventory'; const heading = document.createElement('span'); heading.textContent = '玩家背包'; group.append(heading); PLAYER_TYPES.forEach((type) => { const item = document.createElement('label'); item.className = 'backpack-item'; item.innerHTML = `<span>${iconMarkup(type, tileLabel({ type }), Direction.UP)}</span><small>${TYPE_NAMES[type]}</small>`; const count = document.createElement('input'); count.type = 'number'; count.min = '0'; count.max = type === InstructionTile.CLONE_POINT ? '1' : '999'; count.value = Math.min(type === InstructionTile.CLONE_POINT ? 1 : Infinity, inventory[type] || 0); count.addEventListener('change', () => { inventory[type] = Math.min(type === InstructionTile.CLONE_POINT ? 1 : 999, Math.max(0, Number(count.value) || 0)); count.value = inventory[type]; level.inventory = cloneLevel(inventory); }); item.append(count); group.append(item); }); palette.append(group); }
function editCell(world, pos) { if (running || simulation.status === 'won' || simulation.status === 'lost') return; const tiles = world === 'instruction' ? level.instruction.tiles : level.execution.tiles; const k = key(pos); const old = tiles[k]; if (!designMode && isEliminationLevel()) { if (world !== 'execution' || !eliminationPalette.some(([type]) => type === selected.type) || (old && ![ExecutionTile.RED, ExecutionTile.BLUE].includes(old.type))) return; if (selected.type === 'eraseExecution') delete tiles[k]; else tiles[k] = { type: selected.type, direction: Direction.RIGHT, preset: false }; reset(); return; } if ((world === 'instruction' && !isInstructionTile(selected.type)) || (world === 'execution' && !isExecutionTile(selected.type))) return; if (!designMode && world !== 'instruction') return; if (!designMode && (old?.preset || old?.type === InstructionTile.BARRIER)) return; if (world === 'execution' && selected.type === 'execRobot') { level.execution.robot = { position: pos, direction: selected.direction }; reset(); return; } if (selected.type === 'erase' || selected.type === 'eraseExecution') { if (!designMode && old) returnToInventory(old); delete tiles[k]; } else { if (!designMode && (!PLAYER_TYPES.includes(selected.type) || (inventory[selected.type] || 0) <= 0)) return; if (!designMode && old) returnToInventory(old); if (!designMode) inventory[selected.type] -= 1; if (world === 'instruction' && selected.type === InstructionTile.CLONE_POINT) Object.keys(tiles).forEach((entry) => { if (entry !== k && tiles[entry].type === InstructionTile.CLONE_POINT) { if (!designMode) returnToInventory(tiles[entry]); delete tiles[entry]; } }); if (world === 'execution' && selected.type === ExecutionTile.FINISH) Object.keys(tiles).forEach((entry) => { if (tiles[entry].type === ExecutionTile.FINISH) delete tiles[entry]; }); tiles[k] = { ...selected, preset: world === 'instruction' && designMode && selected.type !== InstructionTile.BARRIER }; } reset(); }
function update() { renderGrid(instructionGrid, 'instruction'); renderInstructionEntry(); renderGrid(executionGrid, 'execution'); renderPalette(); renderInventory(); renderSavePanel(); const snap = simulation.snapshot(); const message = { ready: '准备就绪', running: '运行中', won: '通关！', lost: '失败：路径已耗尽' }[snap.status]; $('levelName').textContent = `${level.meta.id} · ${level.meta.name}`; $('executionDescription').textContent = isEliminationLevel() ? '特殊目标：通过布置红、蓝地板，使所有指令机器人因碰撞或坠落而消失。' : ''; $('editHint').textContent = isEliminationLevel() && !designMode ? '本关仅可编辑执行模块；红色与蓝色地板数量无限。' : ''; $('levelStatus').hidden = designMode; $('statusText').textContent = message; $('statusText').className = snap.status; $('stepCount').textContent = snap.steps; $('executionState').textContent = `(${snap.execution.position.x + 1}, ${snap.execution.position.y + 1}) · ${DIR_NAMES[snap.execution.direction]}`; $('cloneCount').textContent = snap.waiting.length; $('eventLog').replaceChildren(...snap.events.slice(0, 8).map(({ step, message }) => { const li = document.createElement('li'); li.innerHTML = `<span>${String(step).padStart(2, '0')}</span>${message}`; return li; })); $('runButton').textContent = running ? '暂停运行' : snap.status === 'ready' ? '开始运行' : '继续运行'; $('stepButton').disabled = running || snap.status === 'won' || snap.status === 'lost'; }
function doStep() { simulation.step(); if (simulation.status === 'won') { stop(); saveClearHistory(); } if (simulation.status === 'lost') stop(); update(); if (simulation.snapshot().visuals.length) setTimeout(() => { simulation.visuals = []; update(); }, 460); }
function stop() { running = false; clearInterval(timer); timer = null; }
function reset() { stop(); simulation = new Simulation(level); update(); }
function toggleDesignMode() { designMode = !designMode; if (!designMode) { inventory.clonePoint = Math.min(1, inventory.clonePoint || 0); level.inventory = cloneLevel(inventory); inventory = cloneLevel(level.inventory); } update(); }
$('stepButton').onclick = doStep; $('runButton').onclick = () => { if (running) { stop(); update(); } else { if (simulation.status === 'won' || simulation.status === 'lost') reset(); simulation.begin(); running = true; timer = setInterval(doStep, 280); update(); } }; $('resetButton').onclick = reset; $('closeLevelDialog').onclick = () => $('levelDialog').close();
document.addEventListener('keydown', (event) => { if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === 'd') { event.preventDefault(); toggleDesignMode(); } });
update();
loadLevel('-4-熟悉规则01');
